name: test
on: [push, pull_request]
jobs:
  test:
    name: Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 17.x]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm i
    - name: npm test
      run: npm test
    - name: npm run lint
      run: npm run lint
